# NumPy Exercises

## Importing NumPy

In [ ]:
import numpy as np

## Task 1
Write a single line of code to extract all numbers from the given NumPy array which are strictly less than a specified number.

The task is to write **a single line of code** to print the numbers from the *numbers* array which are strictly less than *n*, that is, the numbers which are strictly less than 5. Write the code inside the print statement given below. The code should work for any array *numbers* and for any value of *n*, so use variables only, and not constants like 5.

The output for the given array should be :


```
[2.7 4.9 1.4 2.8]
```



In [5]:
import numpy as np

numbers = np.array([[5.0, 2.7, 5.1],
                  [4.9, 6.2, 8.5],
                  [1.4, 2.8, 9.5]])
print("Given array : \n", numbers)
n = 5

print(numbers[numbers<5]) 

Given array : 
 [[5.  2.7 5.1]
 [4.9 6.2 8.5]
 [1.4 2.8 9.5]]
[2.7 4.9 1.4 2.8]


## Task 2
Write a single line of code to create an array of 15 sixes. You may only use the numpy.ones() function, and no other function may be used.

In [9]:
import numpy as np

array_of_sixes =  6*(np.ones(15))

print(array_of_sixes)

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


Th output of the above print statement should be :


```
[6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
```



## Task 3
Compute element-wise reciprocal of the given array. Do not use any functions. Write only 1 line of code.

In [10]:
import numpy as np

orig_Array = np.array([1, 2, 3.5, 9.2])

print(1/(orig_Array))  

[1.         0.5        0.28571429 0.10869565]


The output of the above print statement should be :


```
[1.         0.5        0.28571429 0.10869565]
```



## Task 4
Create a 4 x 2 x 3 3D-array of numbers from 4 to 27 (both inclusive). Use exactly two functions of NumPy to accomplish this. Write only one line of code.

In [4]:
import numpy as np

mat_24 = np.arange(4,28).reshape(4,2,3)
print(mat_24)




[[[ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]

 [[22 23 24]
  [25 26 27]]]


The output of the above print statement should be :


```
[[[ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]

 [[22 23 24]
  [25 26 27]]]
```



## Task 5
Swap the first and the last, and the second and the third columns from the given 4x4 matrix. Write your code in one line and don't use any functions.

In [6]:
import numpy as np

orig = np.arange(16, dtype='int').reshape(-1, 4)
print("Original matrix : \n", orig)

orig[:,[0,3]] = orig[:,[3,0]]
orig[:,[1,2]] = orig[:,[2,1]]

print("FInal answer: \n", orig) # Write your 1 line of code inside the print() statement

Original matrix : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
FInal answer: 
 [[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


The output of the above print statement should be :


```
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
```



## Task 6
Create a matrix of dimensions m x n, with 0 being the values on the border, and all the values inside being 1. You may write maximum of 2 lines of code. The matrix name should be *mn_array*. It should work for any values of m and n. You are only allowed to use the numpy.zeros() function.

In [1]:
import numpy as np

m = 9
n = 7

mn_array = np.zeros(63).reshape(m,n)
mn_array[1:8,1:6]=1

   


####

print(mn_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


The output of the above print() statement should be :


```
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
```



## Task 7
Get the value 78 from the given 3D array by indexing.

In [17]:
import numpy as np

arr = np.array([[[34, 22, 3],
                 [41, 25, 23]],
                [[67, 28, 91],
                 [110, 11, 21]],
                [[16, 112, 44],
                 [78, 20, 12]]])

print(arr[2,1,0]) # Using indexing to get the element 78 from the array

78


The output of the above print() statement should be :


```
78
```



## Task 8
Find the weighted average of the given array using only the ndarray.sum() function. Write only 1 line of code. It should work for any weights or array values.

In [64]:
import numpy as np

orig_a = np.array([11, 12, 13, 14, 15, 16])
weights = np.array([-1, 4, 5, 2, 9, 1])

print(np.average(orig_a,weights=weights)) # Write 1 line of code inside the print statement

14.05


The output of the above print() statement should be :


```
14.05
```



## Task 9
Calculate the difference between the maximum and the minimum values of a given array along the third axis. Use only the ndarray.min() and ndarray.max() functions. Write only 1 line of code.

In [36]:
import numpy as np

Orig_array = np.array([[[13, 21, 12],
                        [76, 10, 25],
                        [63, 17, 82],
                        [19, 130, 115],
                        [122, 134, 124],
                        [159, 176, 174]],
                       [[18, 191, 202],
                        [21, 222, 23],
                        [214, 25, 246],
                        [27, 8, 29],
                        [30, 31, 3],
                        [3, 34, 35]]])
print("Original array : \n", Orig_array)

print(Orig_array.min(axis=2),Orig_array.max(axis=2)) # Write 1 line of code inside the print() statement

Original array : 
 [[[ 13  21  12]
  [ 76  10  25]
  [ 63  17  82]
  [ 19 130 115]
  [122 134 124]
  [159 176 174]]

 [[ 18 191 202]
  [ 21 222  23]
  [214  25 246]
  [ 27   8  29]
  [ 30  31   3]
  [  3  34  35]]]
[[ 12  10  17  19 122 159]
 [ 18  21  25   8   3   3]] [[ 21  76  82 130 134 176]
 [202 222 246  29  31  35]]


The output of the above print() statement should be :


```
[[  9  66  65 111  12  17]
 [184 201 221  21  28  32]]
```



## Task 10
Create a linear scale (arithmetic progression) with n points starting from a, with a common difference of d. Calculate the standard deviation of an array of exponentials of each element of the linear scale. Write only 1 line of code. It should work for any values of n, a, and d.

In [1]:
import numpy as np

n = 10
a = 3
d = 7

e= 2.71828 
print(np.std(e**(np.arange(a,(a+(n-1)*d)+1,d))))

1.3819550356002658e+28


The output of the above print() statement should be :


```
1.3820163896209162e+28
```



## Major Task
First, create a chessboard of size n x n using NumPy. n can have any value, even or odd. If the square is black, its value should be 1, else, it should be 0. Now, we have an array of locations where some chess pieces are. Print whether the locations are black squares, or white. You will be given an array for score. If the piece is on a white square, print the median of that particular piece's row as the score for that piece. If it is on a black square, print the sum of the square roots of the column of that piece. Add up all the scores obtained and print it as the final score. It should work for any and all values of n, locations, and scores.

In [ ]:
import numpy as np

n = 9
locations = [(1, 2), (3, 2), (7, 6), (2, 4), (8, 8)] # Locations are in format (Row, Column) with indexing starting from 0
scores = np.arange(n*n).reshape((n, n))
print("Score Table : \n", scores)

Score Table : 
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [49]:
import numpy as np

n = 9
locations = [(1, 2), (3, 2), (7, 6), (2, 4), (8, 8)] # Locations are in format (Row, Column) with indexing starting from 0
scores = np.arange(n*n).reshape((n, n))

chessboard = np.zeros((9,9),int)
for j in range(9):
    for k in range(9):
            if (j+k) % 2 == 1:
                    chessboard[j,k] = 1

###
print(chessboard)

[[0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]


The output of the above print() statement should be :


```
[[0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]
```



In [147]:

import numpy as np


locations = np.array([(1, 2), (3, 2), (7, 6), (2, 4), (8, 8)])

for p in range(5): 
    
    s = locations[p,0]
    r = locations[p,1]
    l = r + s
    if l%2 == 0:
        print("White")
    else:
        print("Black")
    
    


Black
Black
Black
White
White


The output of the above code should be :


```
BLACK
BLACK
BLACK
WHITE
WHITE
```



In [1]:

import numpy as np
n = 9
scores = np.arange(n*n).reshape((n, n))
print("Score Table : \n", scores)
locations = np.array([(1, 2), (3, 2), (7, 6), (2, 4), (8, 8)])
t = 0
for p in range(5): 
    
    s = locations[p,0]
    r = locations[p,1]
    l = r + s
    if l%2 == 0:
        
        x = scores[s].tolist()
        
        y = len(x)
        if y%2 == 0:
            m1 = x[y//2]
            m2 = x[y//2-1]
            m = m1 + m2
            
        else:
            m = x[y//2]
        print(m)
        t = t + m
       
  
        
        
    else:
        
        f = scores[:,r].tolist()
        
        k = np.sum(np.sqrt(f))
        #g = [f**0.5 for f in f]
        
       # k = sum(g)
        print(k)
        t = t+k
print(t)
        
        
    
    
    


Score Table : 
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
51.75610550712166
51.75610550712166
55.47253576970645
22
76
256.98474678394973


The output of the above code should be :


```
51.75610550712166
51.75610550712166
55.47253576970644
22.0
76.0
-------
TOTAL Score =  256.98474678394973
```

